### ISSUE TITLE
F.cache Referential Transparency BUG

### ISSUE THREAD

**Issue by tusharmath** [fluture-js/Fluture#323] opened 2019-04-06 06:52 UTC
It seems like `F.cache` is not referentially transparent. Which is quite evident since calling `F.cache` causes side-effects without forking.

### Steps to reproduce
1. Create two Futures `a` & `b`.
2. For `a` use `F.cache` at the time of creation.
3. For `b` use `F.cache` at the time of usage.
4. Fork both of them.

### Actual
`a` executes only once but `b` executes for each usage.

### Expected
Both `a` and `b` should behave exactly the same ie. execute once.

### Demo Code

```js
const F = require('fluture');


// F.cache is used
let countA = 0
const a = F.cache(F.try(() => ++countA))
a.chain(() => a).fork(console.log, res => console.log('A: ' + res))


// F.cache is NOT used, instead used inside the chain operation
let countB = 0
const b = F.try(() => ++countB)
b.chain(() => F.cache(b)).fork(console.log, res => console.log('B: ' + res))
```

The running example is presented here — 
https://runkit.com/5c204c607117700012dd27ee/5ca847169637970013fe05bb

**Comment by Avaq** [comment] 2019-04-06 09:25
Hi @tusharmath. Thank you for taking the trouble to create such an thorough report. However, the behavior you're describing is both intentional, and documented. From the [`cache` docs](https://github.com/fluture-js/Fluture#cache):

> There is a glaring drawback to using `cache`, which is that returned Futures are no longer referentially transparent, making reasoning about them more difficult and refactoring code that uses them harder.

If you believe that the documentation in its current form is unclear, I'm open to suggestions for improving it, but `cache` is working as intended.

**Comment by tusharmath** [comment] 2019-04-06 14:44
Whoops! Why would u not want it to be referentially transparent though? I guess then this should be a feature request.

**Comment by Avaq** [comment] 2019-04-07 07:47
> this should be a feature request

A feature request for a referentially transparent memoization function?

**Comment by Avaq** [comment] 2019-04-07 10:06
> Why would u not want it to be referentially transparent though?

For the `cache` function, the non-referential-transparency *is* its feature. It's a function you use to work around the drawback\* that a lazy computation underlying a value is reevaluated in all contexts it's used.

What I'm trying to say is that you must choose between a unicast, immutable, referentially transparent value; *or* an eager, multicast, mutable value. Fluture provides the former by default, and `cache` is like an escape hatch to the latter.

\* Of course it's not a drawback once you learn to harness it. Generally, I advise against using `cache` altogether. It's not "idiomatic Fluture" (if that's a thing). It's more like a stepping stone for those who are used to working with multicast values, such as Promises, and consider the referential transparency a drawback.

**Comment by Avaq** [comment] 2019-05-07 16:13
Closing as non-actionable.

**Closed by Avaq** 2019-05-07 16:13 UTC
