### ISSUE TITLE
Error thrown when using same cached Future within Future.parallel

### ISSUE THREAD

**Issue by jonwhelan** [fluture-js/Fluture#362] opened 2019-08-20 23:33 UTC
Hi, I'm running into a possible bug here when referencing a cached future more than once from within a call to `Future.parallel` and then adding some sort of continuation onto it (e.g. `map`, `mapRej`, etc.).

```js
const Future = require('fluture');
const noop = () => {};

const cachedFuture = Future.cache(Future.rejectAfter(1, new Error));

Future
	.parallel(Infinity, [cachedFuture, cachedFuture])
	.map(() => true)
	.fork(noop, noop);
```

This code will throw `TypeError: Cannot read property 'rejected' of null`.

Expected behavior is that this does not throw an error. What's interesting to me is that if you remove the `.map` call or use a cached future that is rejected right away i.e. `Future.cache(Future.reject(new Error))` then it'll work.

**Comment by Avaq** [comment] 2019-08-21 09:23
Thank you for the report! I'll look into this.

**Comment by Avaq** [comment] 2019-08-21 09:32
Confirmed in stable and beta.

**Comment by Avaq** [comment] 2019-08-21 18:17
I identified the cause of the issue. I will submit the PR soon.

**Comment by Avaq** [comment] 2019-08-21 19:27
I'll release the fix under `11.0.3`.

**Comment by Avaq** [comment] 2019-08-21 19:38
The fix has been released to stable. I will continue to merge it upstream.

**Closed** 2019-08-21 20:05 UTC
Labels: bug

**Comment by jonwhelan** [comment] 2019-08-21 20:18
Great! I appreciate the quick fix on this!
